### ISSUE TITLE
Importing files with edges/faces with 4 or more vertices.

### ISSUE THREAD

**Issue by MKloczko** [alextsui05/blender-off-addon#4]
Hello!

I've modified your code to solve the above issue. 
For example meshes generated with powercrust algorithm had sometimes edges, sometimes faces with 4 or more vertices, all in .OFF format.

Would you mind merging the fix into this repository ?

**Comment by alextsui05** [comment]
Hey, thanks for the effort! This sounds like a great feature. If you open a pull request, I'll be happy to look it over.

**Comment by alextsui05** [comment]
I merged your pull request. I also updated the blender wiki page with your details. Thank you again.
