### ISSUE TITLE
The off plugin crashes when there is an empty line between header and the data

### ISSUE THREAD

**Issue by phdggg** [alextsui05/blender-off-addon#6]
The off plugin will crash Blender  when there is an empty line between header and the data. The empty line is very common for .off file.
Please try the attached example.
[sphere.zip](https://github.com/alextsui05/blender-off-addon/files/93777/sphere.zip)

**Comment by alextsui05** [comment]
Sorry for being a deadbeat maintainer.

I checked the file and it is now working in the current master version. For reference it was fixed in this commit:

https://github.com/alextsui05/blender-off-addon/commit/efc842cc8ebd5f87bf29e6e593cbddf1ee69a0d2#diff-7e6071f4f2d3b8a164c983e1e81f5d98
